# Use an official Nginx base image
FROM nginx:alpine

# Copy your HTML files into the Nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Nginx will serve the static site by default