apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy  # <-- Dynamic name per release
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}  # <-- From values.yaml
  selector:
    matchLabels:
      app: {{ .Release.Name }}  # <-- Matches service selector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}  # <-- Unique per release
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret | quote }}  # <-- Uses values.yaml: existingSecret
