apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dbUsername: {{ .Values.dbUsername | b64enc | quote }}
  dbPassword: {{ .Values.dbPassword | b64enc | quote }}
  apiKey: {{ .Values.apiKey | b64enc | quote }}