apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dbUsername: {{ .Values.dbUsername | default "admin" | quote | b64enc }}
  dbPassword: {{ .Values.dbPassword | default "changeme123" | quote | b64enc }}
  apiKey: {{ .Values.apiKey | default "fake-api-key" | quote | b64enc }}