apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dbUsername: {{ .Values.dbUsername | default "admin" | b64enc | quote }}
  dbPassword: {{ .Values.dbPassword | default "Password1234A" | b64enc | quote }}
  apiKey: {{ .Values.apiKey | default "fake-api-key" | b64enc | quote }}