apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc  # <-- Dynamic naming for Helm releases (blue/green)
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}     # <-- Must match the app label in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
