apiVersion: v1
kind: Service
metadata:
  name: cloudnorth-backend-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: cloudnorth-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080