apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnorth-grafana
  namespace: monitoring  # <-- Added this line to ensure it's deployed in the correct namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnorth-grafana
  template:
    metadata:
      labels:
        app: cloudnorth-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_HTTP_ADDR
              value: "0.0.0.0"
          volumeMounts:
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      volumes:
        - name: grafana-datasource
          configMap:
            name: cloudnorth-grafana-datasource