apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudnorth-grafana-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: false