apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnorth-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnorth-grafana
  template:
    metadata:
      labels:
        app: cloudnorth-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.4.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      volumes:
        - name: grafana-datasource
          configMap:
            name: cloudnorth-grafana-datasource