[agent]
  collection_jitter = "0s"
  debug = false
  flush_interval = "1s"
  flush_jitter = "0s"
  hostname = ""
  interval = "60s"
  logfile = "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
  logtarget = "lumberjack"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = false
  precision = ""
  quiet = false
  round_interval = false
  run_as_user = "root"

[inputs]

  [[inputs.cpu]]
    fieldpass = ["usage_idle", "usage_user", "usage_system"]
    interval = "60s"
    percpu = false
    totalcpu = true

  [[inputs.disk]]
    fieldpass = ["used_percent"]
    interval = "60s"
    tagexclude = ["mode"]

  [[inputs.logfile]]
    destination = "cloudwatchlogs"
    file_state_folder = "/opt/aws/amazon-cloudwatch-agent/logs/state"

    [[inputs.logfile.file_config]]
      deployment_environment = ""
      file_path = "/var/log/syslog"
      from_beginning = true
      log_group_class = ""
      log_group_name = "cloudnorth-app-logs"
      log_stream_name = "i-040c6dd93f9941cba/syslog"
      pipe = false
      retention_in_days = -1
      service_name = ""
      timestamp_layout = ["Jan _2 15:04:05"]
      timestamp_regex = "(\\w{3} \\s{0,1}\\d{1,2} \\d{2}:\\d{2}:\\d{2})"

    [[inputs.logfile.file_config]]
      deployment_environment = ""
      file_path = "/var/log/jenkins/jenkins.log"
      from_beginning = true
      log_group_class = ""
      log_group_name = "cloudnorth-app-logs"
      log_stream_name = "i-040c6dd93f9941cba/jenkins"
      pipe = false
      retention_in_days = -1
      service_name = ""
      timestamp_layout = ["2006-01-_2 15:04:05", "2006-1-_2 15:04:05"]
      timestamp_regex = "(\\d{4}-\\s{0,1}\\d{1,2}-\\s{0,1}\\d{1,2} \\d{2}:\\d{2}:\\d{2})"

  [[inputs.mem]]
    fieldpass = ["used_percent"]
    interval = "60s"

[outputs]

  [[outputs.cloudwatch]]

  [[outputs.cloudwatchlogs]]
    force_flush_interval = "5s"
    log_stream_name = "i-040c6dd93f9941cba"
    mode = "EC2"
    region = "us-east-1"
    region_type = "EC2M"
