apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnorth-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnorth-prometheus
  template:
    metadata:
      labels:
        app: cloudnorth-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.47.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: cloudnorth-prometheus-config