apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnorth-prometheus
  namespace: monitoring  # <-- ✅ Add this to ensure it's deployed in the correct namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnorth-prometheus
  template:
    metadata:
      labels:
        app: cloudnorth-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.47.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.listen-address=0.0.0.0:9090"
          ports:
            - containerPort: 9090
              hostPort: 9090  # <-- ✅ Exposes it directly on EC2 public IP (not recommended for prod, fine for bootcamp)
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: prometheus-config
          configMap:
            name: cloudnorth-prometheus-config