apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnorth-frontend-deploy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}  # <-- Controlled from values.yaml
  selector:
    matchLabels:
      app: cloudnorth-frontend
  template:
    metadata:
      labels:
        app: cloudnorth-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # <-- Dynamic from values.yaml
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cloudnorth-frontend-config