apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}            # <-- dynamic deployment name
  namespace: {{ .Release.Namespace }}            # <-- auto-handled by Helm release
spec:
  replicas: {{ .Values.replicaCount }}           # <-- controlled from values file
  selector:
    matchLabels:
      app: cloudnorth-frontend
  template:
    metadata:
      labels:
        app: cloudnorth-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"   # <-- dynamic image & tag
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}   # <-- dynamic configmap
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
