{{- if eq .Values.color "blue" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.deployment.name }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudnorth-frontend
    color: {{ .Values.color }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployment.name }}
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
{{- end }}
