{{- if eq .Values.color "blue" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudnorth-frontend-blue-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudnorth-frontend-blue  # Keep for tracking
    color: blue                                        # Added to match values.yaml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudnorth-frontend-blue-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
{{- end }}
