apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  # <-- Dynamic name from values-blue/green.yaml
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cloudnorth-frontend
    color: {{ .Values.color }}       # <-- Ensures blue only talks to blue pods, green to green
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
