apiVersion: v1
kind: Service
metadata:
  name: cloudnorth-frontend-green-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: cloudnorth-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
