replicaCount: 2

image:
  repository: stillfreddie/cloudnorth-backend
  tag: phase4.1
  pullPolicy: Always

deployment:
  name: cloudnorth-backend-green-deploy

service:
  name: cloudnorth-backend-green-svc
  type: ClusterIP
  port: 80

color: green

existingSecret: cloudnorth-backend-green-secret

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
