replicaCount: 2

image:
  repository: stillfreddie/cloudnorth-backend
  tag: phase4.1
  pullPolicy: Always

deployment:
  name: cloudnorth-backend-blue-deploy

service:
  name: cloudnorth-backend-blue-svc
  type: ClusterIP
  port: 80

color: blue

existingSecret: cloudnorth-backend-secret

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
