image:
  repository: stillfreddie/cloudnorth-frontend
  tag: phase4.1
  pullPolicy: Always

deployment:
  name: cloudnorth-frontend-green-deploy-v2

service:
  name: cloudnorth-frontend-green-svc-v2
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

configmap:
  enabled: true
  name: cloudnorth-frontend-config-green-v2

configName: cloudnorth-frontend-config-green-v2

color: green

# This section only makes sense if you're templating a ConfigMap file via Helm
env:
  BACKEND_URL: http://cloudnorth-backend-green-svc
